---
- name: deploy
  command: |
    helm upgrade -i \
    "{{ release_name }}" \
    -f "raw/{{ env }}/values.yaml" \
    "{{ chart }}" \
    --namespace "{{ namespace }}"
  ignore_errors: "{{ ansible_check_mode }}"
